### ISSUE TITLE
Wrong code and Readme description

### ISSUE THREAD

**Issue by smenshikov** [Gsawahji/pumpfun-sniper-bot#1]
In Readme you have 

> Select "Set settings" from the menu to configure your bot settings including:
> Minimum Market Cap
> **Minimum Reply Count
> Require Telegram
> Require Website
> Require Twitter**

few points do not match the source code

**Comment by tigerjiang** [comment]
I can run this demo, can you help me, there is no command for "npm start"

**Comment by smenshikov** [comment]
> I can't run this demo, can you help me, there is no command for "npm start"

I did not run the script. I just saw the code and was confused about readme file and the source code. There is another command in package.json under "scripts" section. 

P.S. I do not trust the source code of this repo

**Comment by smenshikov** [comment]
> I can't run this demo, can you help me, there is no command for "npm start"

Command "npm run fssb", but be careful because you run the code with your private key of your wallet

**Comment by Gsawahji** [comment]
Made a few changes, now it works as planned. Also updated the README.md

**Comment by shoaib-jamal** [comment]
![image](https://github.com/user-attachments/assets/d28258e3-d214-43dc-a7dd-540380931bf2)

Scammer, reported.
